package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/example/payment-federation/internal/app/graph/dataloader"
	"github.com/example/payment-federation/internal/app/graph/generated"
	"github.com/example/payment-federation/internal/app/graph/model"
)

// FindOrderByID is the resolver for the findOrderByID field. Via DataLoader: o
// gateway de federação costuma pedir VÁRIAS entities numa requisição — o loader
// agrupa essas buscas num só GetOrdersByIDs.
func (r *entityResolver) FindOrderByID(ctx context.Context, id string) (*model.Order, error) {
	return dataloader.For(ctx).OrderByID.Load(id)
}

// FindPaymentByID is the resolver for the findPaymentByID field.
func (r *entityResolver) FindPaymentByID(ctx context.Context, id string) (*model.Payment, error) {
	return r.load(ctx, id)
}

// FindUserByID is the resolver for the findUserByID field. Via DataLoader (batch
// das entities User pedidas pela federação).
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return dataloader.For(ctx).UserByID.Load(id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
