package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/example/payment-federation/internal/app/graph/dataloader"
	"github.com/example/payment-federation/internal/app/graph/generated"
	"github.com/example/payment-federation/internal/app/graph/model"
	"github.com/example/payment-federation/internal/payments/application/command"
	"github.com/example/payment-federation/internal/shared/cqrs"
)

// ProcessPayment is the resolver for the processPayment field.
func (r *mutationResolver) ProcessPayment(ctx context.Context, input model.ProcessPaymentInput) (*model.Payment, error) {
	cmd := command.ProcessPayment{
		IdempotencyKey: input.IdempotencyKey,
		CustomerID:     input.CustomerID,
		AmountCents:    input.AmountCents,
		Currency:       input.Currency,
	}
	if input.GatewayName != nil {
		cmd.GatewayName = *input.GatewayName
	}

	// CommandBus genérico -> Watermill (block-until-ack): Dispatch retorna após
	// o use-case ter persistido e publicado os eventos.
	if err := r.Commands.Dispatch(ctx, cmd); err != nil {
		return nil, err
	}
	// Read-after-write pelo read model. Como o id é gerado dentro do handler,
	// relemos pela chave de idempotência que nós mesmos enviamos.
	return r.loadByKey(ctx, input.IdempotencyKey)
}

// RefundPayment is the resolver for the refundPayment field.
func (r *mutationResolver) RefundPayment(ctx context.Context, input model.RefundPaymentInput) (*model.Payment, error) {
	if err := r.Commands.Dispatch(ctx, command.RefundPayment{
		PaymentID:   input.PaymentID,
		AmountCents: input.AmountCents,
	}); err != nil {
		return nil, err
	}
	// Read-after-write pelo id já conhecido do pagamento.
	return r.load(ctx, input.PaymentID)
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	// Despacha CreateOrder (Watermill, block-until-ack). O handler persiste e
	// publica OrderCreated, que dispara o pagamento automaticamente (saga).
	data, err := cqrs.ExecuteCommandSync[command.CreateOrder, command.CreateOrderResult](ctx, r.Commands, command.CreateOrder{
		IdempotencyKey: input.IdempotencyKey,
		CustomerID:     input.CustomerID,
		AmountCents:    input.AmountCents,
		Currency:       input.Currency,
	})
	if err != nil {
		return nil, err
	}
	// Read-after-write pelo idempotencyKey (o id do pedido é gerado no use-case).
	return r.loadOrderByKey(ctx, data.OrderID)
}

// Customer is the resolver for the customer field. Resolve o cliente do pedido
// via DataLoader (batch + cache por requisição) a partir do customerId.
func (r *orderResolver) Customer(ctx context.Context, obj *model.Order) (*model.User, error) {
	return dataloader.For(ctx).UserByID.Load(obj.CustomerID)
}

// Payment is the resolver for the payment field.
func (r *queryResolver) Payment(ctx context.Context, id string) (*model.Payment, error) {
	return r.load(ctx, id)
}

// Order is the resolver for the order field. Resolve via DataLoader (batch +
// cache por requisição) — útil quando o mesmo pedido é referenciado mais de uma
// vez na mesma operação.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	return dataloader.For(ctx).OrderByID.Load(id)
}

// OnPaymentProcessed is the resolver for the onPaymentProcessed field. Devolve
// um canal alimentado pelo PaymentHub, filtrado pelo orderId; o gqlgen transmite
// o Payment ao cliente quando o pagamento daquele pedido for capturado, e encerra
// quando o ctx (subscription) é cancelado.
func (r *subscriptionResolver) OnPaymentProcessed(ctx context.Context, orderID string) (<-chan *model.Payment, error) {
	return r.Payments.Subscribe(ctx, orderID), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
