// Code generated by ent, DO NOT EDIT.

package payment

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldAmountCents holds the string denoting the amount_cents field in the database.
	FieldAmountCents = "amount_cents"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRefundedCents holds the string denoting the refunded_cents field in the database.
	FieldRefundedCents = "refunded_cents"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGatewayRef holds the string denoting the gateway_ref field in the database.
	FieldGatewayRef = "gateway_ref"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// Table holds the table name of the payment in the database.
	Table = "payments"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldIdempotencyKey,
	FieldCustomerID,
	FieldAmountCents,
	FieldCurrency,
	FieldRefundedCents,
	FieldStatus,
	FieldGatewayRef,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	CustomerIDValidator func(string) error
	// DefaultRefundedCents holds the default value on creation for the "refunded_cents" field.
	DefaultRefundedCents int64
	// DefaultGatewayRef holds the default value on creation for the "gateway_ref" field.
	DefaultGatewayRef string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByAmountCents orders the results by the amount_cents field.
func ByAmountCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCents, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRefundedCents orders the results by the refunded_cents field.
func ByRefundedCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedCents, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGatewayRef orders the results by the gateway_ref field.
func ByGatewayRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayRef, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}
