// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/payment"
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/predicate"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentUpdate) SetAmountCents(v int64) *PaymentUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmountCents(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentUpdate) AddAmountCents(v int64) *PaymentUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetRefundedCents sets the "refunded_cents" field.
func (_u *PaymentUpdate) SetRefundedCents(v int64) *PaymentUpdate {
	_u.mutation.ResetRefundedCents()
	_u.mutation.SetRefundedCents(v)
	return _u
}

// SetNillableRefundedCents sets the "refunded_cents" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableRefundedCents(v *int64) *PaymentUpdate {
	if v != nil {
		_u.SetRefundedCents(*v)
	}
	return _u
}

// AddRefundedCents adds value to the "refunded_cents" field.
func (_u *PaymentUpdate) AddRefundedCents(v int64) *PaymentUpdate {
	_u.mutation.AddRefundedCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v string) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGatewayRef sets the "gateway_ref" field.
func (_u *PaymentUpdate) SetGatewayRef(v string) *PaymentUpdate {
	_u.mutation.SetGatewayRef(v)
	return _u
}

// SetNillableGatewayRef sets the "gateway_ref" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableGatewayRef(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetGatewayRef(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdate) SetUpdatedAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUpdatedAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PaymentUpdate) SetVersion(v int) *PaymentUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableVersion(v *int) *PaymentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PaymentUpdate) AddVersion(v int) *PaymentUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(payment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(payment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedCents(); ok {
		_spec.SetField(payment.FieldRefundedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedCents(); ok {
		_spec.AddField(payment.FieldRefundedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayRef(); ok {
		_spec.SetField(payment.FieldGatewayRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(payment.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(payment.FieldVersion, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentUpdateOne) SetAmountCents(v int64) *PaymentUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmountCents(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentUpdateOne) AddAmountCents(v int64) *PaymentUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetRefundedCents sets the "refunded_cents" field.
func (_u *PaymentUpdateOne) SetRefundedCents(v int64) *PaymentUpdateOne {
	_u.mutation.ResetRefundedCents()
	_u.mutation.SetRefundedCents(v)
	return _u
}

// SetNillableRefundedCents sets the "refunded_cents" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableRefundedCents(v *int64) *PaymentUpdateOne {
	if v != nil {
		_u.SetRefundedCents(*v)
	}
	return _u
}

// AddRefundedCents adds value to the "refunded_cents" field.
func (_u *PaymentUpdateOne) AddRefundedCents(v int64) *PaymentUpdateOne {
	_u.mutation.AddRefundedCents(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v string) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetGatewayRef sets the "gateway_ref" field.
func (_u *PaymentUpdateOne) SetGatewayRef(v string) *PaymentUpdateOne {
	_u.mutation.SetGatewayRef(v)
	return _u
}

// SetNillableGatewayRef sets the "gateway_ref" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableGatewayRef(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetGatewayRef(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentUpdateOne) SetUpdatedAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUpdatedAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PaymentUpdateOne) SetVersion(v int) *PaymentUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableVersion(v *int) *PaymentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PaymentUpdateOne) AddVersion(v int) *PaymentUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(payment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(payment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedCents(); ok {
		_spec.SetField(payment.FieldRefundedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedCents(); ok {
		_spec.AddField(payment.FieldRefundedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayRef(); ok {
		_spec.SetField(payment.FieldGatewayRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(payment.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(payment.FieldVersion, field.TypeInt, value)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
