// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/payment"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *PaymentCreate) SetIdempotencyKey(v string) *PaymentCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetCustomerID sets the "customer_id" field.
func (_c *PaymentCreate) SetCustomerID(v string) *PaymentCreate {
	_c.mutation.SetCustomerID(v)
	return _c
}

// SetAmountCents sets the "amount_cents" field.
func (_c *PaymentCreate) SetAmountCents(v int64) *PaymentCreate {
	_c.mutation.SetAmountCents(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentCreate) SetCurrency(v string) *PaymentCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetRefundedCents sets the "refunded_cents" field.
func (_c *PaymentCreate) SetRefundedCents(v int64) *PaymentCreate {
	_c.mutation.SetRefundedCents(v)
	return _c
}

// SetNillableRefundedCents sets the "refunded_cents" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableRefundedCents(v *int64) *PaymentCreate {
	if v != nil {
		_c.SetRefundedCents(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentCreate) SetStatus(v string) *PaymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetGatewayRef sets the "gateway_ref" field.
func (_c *PaymentCreate) SetGatewayRef(v string) *PaymentCreate {
	_c.mutation.SetGatewayRef(v)
	return _c
}

// SetNillableGatewayRef sets the "gateway_ref" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableGatewayRef(v *string) *PaymentCreate {
	if v != nil {
		_c.SetGatewayRef(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentCreate) SetCreatedAt(v time.Time) *PaymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentCreate) SetUpdatedAt(v time.Time) *PaymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PaymentCreate) SetVersion(v int) *PaymentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentCreate) SetID(v string) *PaymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PaymentMutation object of the builder.
func (_c *PaymentCreate) Mutation() *PaymentMutation {
	return _c.mutation
}

// Save creates the Payment in the database.
func (_c *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCreate) defaults() {
	if _, ok := _c.mutation.RefundedCents(); !ok {
		v := payment.DefaultRefundedCents
		_c.mutation.SetRefundedCents(v)
	}
	if _, ok := _c.mutation.GatewayRef(); !ok {
		v := payment.DefaultGatewayRef
		_c.mutation.SetGatewayRef(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCreate) check() error {
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "Payment.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := payment.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "Payment.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Payment.customer_id"`)}
	}
	if v, ok := _c.mutation.CustomerID(); ok {
		if err := payment.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Payment.customer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "Payment.amount_cents"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Payment.currency"`)}
	}
	if _, ok := _c.mutation.RefundedCents(); !ok {
		return &ValidationError{Name: "refunded_cents", err: errors.New(`ent: missing required field "Payment.refunded_cents"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Payment.status"`)}
	}
	if _, ok := _c.mutation.GatewayRef(); !ok {
		return &ValidationError{Name: "gateway_ref", err: errors.New(`ent: missing required field "Payment.gateway_ref"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Payment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Payment.updated_at"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Payment.version"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := payment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Payment.id": %w`, err)}
		}
	}
	return nil
}

func (_c *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Payment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(payment.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.CustomerID(); ok {
		_spec.SetField(payment.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := _c.mutation.AmountCents(); ok {
		_spec.SetField(payment.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RefundedCents(); ok {
		_spec.SetField(payment.FieldRefundedCents, field.TypeInt64, value)
		_node.RefundedCents = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GatewayRef(); ok {
		_spec.SetField(payment.FieldGatewayRef, field.TypeString, value)
		_node.GatewayRef = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(payment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(payment.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (_c *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Payment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
