// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/order"
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/payment"
	"github.com/example/payment-federation/internal/payments/infrastructure/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescIdempotencyKey is the schema descriptor for idempotency_key field.
	orderDescIdempotencyKey := orderFields[1].Descriptor()
	// order.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	order.IdempotencyKeyValidator = orderDescIdempotencyKey.Validators[0].(func(string) error)
	// orderDescCustomerID is the schema descriptor for customer_id field.
	orderDescCustomerID := orderFields[2].Descriptor()
	// order.CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	order.CustomerIDValidator = orderDescCustomerID.Validators[0].(func(string) error)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderFields[0].Descriptor()
	// order.IDValidator is a validator for the "id" field. It is called by the builders before save.
	order.IDValidator = orderDescID.Validators[0].(func(string) error)
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescIdempotencyKey is the schema descriptor for idempotency_key field.
	paymentDescIdempotencyKey := paymentFields[1].Descriptor()
	// payment.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	payment.IdempotencyKeyValidator = paymentDescIdempotencyKey.Validators[0].(func(string) error)
	// paymentDescCustomerID is the schema descriptor for customer_id field.
	paymentDescCustomerID := paymentFields[2].Descriptor()
	// payment.CustomerIDValidator is a validator for the "customer_id" field. It is called by the builders before save.
	payment.CustomerIDValidator = paymentDescCustomerID.Validators[0].(func(string) error)
	// paymentDescRefundedCents is the schema descriptor for refunded_cents field.
	paymentDescRefundedCents := paymentFields[5].Descriptor()
	// payment.DefaultRefundedCents holds the default value on creation for the refunded_cents field.
	payment.DefaultRefundedCents = paymentDescRefundedCents.Default.(int64)
	// paymentDescGatewayRef is the schema descriptor for gateway_ref field.
	paymentDescGatewayRef := paymentFields[7].Descriptor()
	// payment.DefaultGatewayRef holds the default value on creation for the gateway_ref field.
	payment.DefaultGatewayRef = paymentDescGatewayRef.Default.(string)
	// paymentDescID is the schema descriptor for id field.
	paymentDescID := paymentFields[0].Descriptor()
	// payment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	payment.IDValidator = paymentDescID.Validators[0].(func(string) error)
}
