// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "customer_id", Type: field.TypeString},
		{Name: "amount_cents", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "version", Type: field.TypeInt},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString, Unique: true},
		{Name: "customer_id", Type: field.TypeString},
		{Name: "amount_cents", Type: field.TypeInt64},
		{Name: "currency", Type: field.TypeString},
		{Name: "refunded_cents", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeString},
		{Name: "gateway_ref", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "version", Type: field.TypeInt},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OrdersTable,
		PaymentsTable,
	}
)

func init() {
}
