// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)
