package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/example/payment-federation/internal/interfaces/graph/generated"
	"github.com/example/payment-federation/internal/interfaces/graph/model"
	"github.com/example/payment-federation/internal/payments/application/command"
)

// ProcessPayment is the resolver for the processPayment field.
func (r *mutationResolver) ProcessPayment(ctx context.Context, input model.ProcessPaymentInput) (*model.Payment, error) {
	cmd := command.ProcessPayment{
		IdempotencyKey: input.IdempotencyKey,
		CustomerID:     input.CustomerID,
		AmountCents:    input.AmountCents,
		Currency:       input.Currency,
	}
	if input.GatewayName != nil {
		cmd.GatewayName = *input.GatewayName
	}

	// CommandBus genérico -> Watermill (block-until-ack): Dispatch retorna após
	// o use-case ter persistido e publicado os eventos.
	if err := r.Commands.Dispatch(ctx, cmd); err != nil {
		return nil, err
	}
	// Read-after-write pelo read model. Como o id é gerado dentro do handler,
	// relemos pela chave de idempotência que nós mesmos enviamos.
	return r.loadByKey(ctx, input.IdempotencyKey)
}

// RefundPayment is the resolver for the refundPayment field.
func (r *mutationResolver) RefundPayment(ctx context.Context, input model.RefundPaymentInput) (*model.Payment, error) {
	if err := r.Commands.Dispatch(ctx, command.RefundPayment{
		PaymentID:   input.PaymentID,
		AmountCents: input.AmountCents,
	}); err != nil {
		return nil, err
	}
	// Read-after-write pelo id já conhecido do pagamento.
	return r.load(ctx, input.PaymentID)
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	// Despacha CreateOrder (Watermill, block-until-ack). O handler persiste e
	// publica OrderCreated, que dispara o pagamento automaticamente (saga).
	if err := r.Commands.Dispatch(ctx, command.CreateOrder{
		IdempotencyKey: input.IdempotencyKey,
		CustomerID:     input.CustomerID,
		AmountCents:    input.AmountCents,
		Currency:       input.Currency,
	}); err != nil {
		return nil, err
	}
	// Read-after-write pelo idempotencyKey (o id do pedido é gerado no use-case).
	return r.loadOrderByKey(ctx, input.IdempotencyKey)
}

// Payment is the resolver for the payment field.
func (r *queryResolver) Payment(ctx context.Context, id string) (*model.Payment, error) {
	return r.load(ctx, id)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	return r.loadOrder(ctx, id)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
