package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/example/payment-federation/internal/interfaces/graph/model"
	usercmd "github.com/example/payment-federation/internal/user/application/command"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	if err := r.Commands.Dispatch(ctx, usercmd.CreateUser{
		Name:  input.Name,
		Email: input.Email,
	}); err != nil {
		return nil, err
	}
	// Read-after-write pelo e-mail (chave natural única); o id é gerado no use-case.
	return r.loadUserByEmail(ctx, input.Email)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	if err := r.Commands.Dispatch(ctx, usercmd.UpdateUser{
		UserID: input.ID,
		Name:   input.Name,
		Email:  input.Email,
	}); err != nil {
		return nil, err
	}
	return r.loadUser(ctx, input.ID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.loadUser(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.listUsers(ctx)
}
